# Minimal pandas typing shim for mypy in this repo.
# It intentionally treats pandas symbols as Any to avoid noisy errors from
# dynamic import shims and the small fallback stub used at runtime.
from typing import Any, Iterable, Dict, List, Optional, Union

DataFrame: Any
Series: Any

def read_csv(path: object, *args: object, **kwargs: object) -> Any: ...
def read_json(path: object, *args: object, **kwargs: object) -> Any: ...
def to_datetime(arg: object, *args: object, **kwargs: object) -> Any: ...
def to_numeric(arg: object, *args: object, **kwargs: object) -> Any: ...
def concat(objs: Iterable[Any], *args: object, **kwargs: object) -> Any: ...
def isna(obj: object) -> Any: ...

def date_range(*args: object, **kwargs: object) -> Any: ...

# give DataFrame a minimal attribute so expressions like pd.DataFrame.from_records
# type-check as having an attribute
class _DataFrame:
    @staticmethod
    def from_records(records: Iterable[Dict[str, Any]]) -> Any: ...

DataFrame = _DataFrame  # type: ignore
