# Minimal typing shim for requests used locally to reduce mypy noise in this repo
from typing import Any

def get(*args: Any, **kwargs: Any) -> Any: ...
def post(*args: Any, **kwargs: Any) -> Any: ...

class Session:
	def get(self, *args: object, **kwargs: object) -> object: ...
	def post(self, *args: object, **kwargs: object) -> object: ...
	def mount(self, *args: object, **kwargs: object) -> object: ...
	headers: object

