#!/usr/bin/env python3
"""
Test script to verify the signal generation and backtesting functionality.
"""

import sys
import os
import tempfile
import pandas as pd
import numpy as np
from datetime import datetime, timezone, timedelta

# Add repo to path
repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.append(repo_root)

def create_synthetic_data(bars=100, trend_up=True):
    """Create synthetic OHLCV data for testing."""
    # Start with a base price
    base_price = 50000.0
    dates = pd.date_range(start='2024-01-01', periods=bars, freq='h')
    
    # Generate trending price data
    if trend_up:
        # Upward trend with some noise
        trend = np.linspace(0, 0.2, bars)  # 20% total increase
        noise = np.random.normal(0, 0.01, bars)  # 1% noise
        price_multiplier = 1 + trend + noise
    else:
        # Sideways with some oscillation
        oscillation = 0.05 * np.sin(np.linspace(0, 4*np.pi, bars))
        noise = np.random.normal(0, 0.005, bars)
        price_multiplier = 1 + oscillation + noise
    
    # Calculate OHLCV
    close_prices = base_price * price_multiplier
    
    # Generate OHLC with some realistic patterns
    open_prices = np.roll(close_prices, 1)
    open_prices[0] = close_prices[0]
    
    high_multiplier = 1 + np.abs(np.random.normal(0, 0.005, bars))
    low_multiplier = 1 - np.abs(np.random.normal(0, 0.005, bars))
    
    high_prices = np.maximum(open_prices, close_prices) * high_multiplier
    low_prices = np.minimum(open_prices, close_prices) * low_multiplier
    
    volumes = np.random.uniform(10, 100, bars)
    
    df = pd.DataFrame({
        'open': open_prices,
        'high': high_prices,
        'low': low_prices,
        'close': close_prices,
        'volume': volumes
    }, index=dates)
    
    return df

def test_signal_generation():
    """Test the signal generation functions."""
    print("Testing signal generation...")
    
    # Import with proper path handling
    from scripts.run_backtest import import_third_party
    from tradingbot_ibkr.signal_generators import generate_signals, generate_enhanced_signals, generate_breakout_signals
    
    # Create upward trending data (should generate SMA crossover signals)
    df = create_synthetic_data(bars=200, trend_up=True)
    
    # Test basic SMA crossover
    signals = generate_signals(df)
    signal_count = signals['signals'].sum()
    signal_pct = signals['signals'].mean() * 100
    
    print(f"SMA Crossover Signals:")
    print(f"  Total signals: {signal_count}")
    print(f"  Signal percentage: {signal_pct:.2f}%")
    
    # Test enhanced signals
    enhanced = generate_enhanced_signals(df)
    enhanced_count = enhanced['signals'].sum()
    enhanced_pct = enhanced['signals'].mean() * 100
    
    print(f"Enhanced Signals:")
    print(f"  Total signals: {enhanced_count}")
    print(f"  Signal percentage: {enhanced_pct:.2f}%")
    
    # Test breakout signals
    breakout = generate_breakout_signals(df, lookback_period=10)
    breakout_count = breakout['signals'].sum()
    breakout_pct = breakout['signals'].mean() * 100
    
    print(f"Breakout Signals:")
    print(f"  Total signals: {breakout_count}")
    print(f"  Signal percentage: {breakout_pct:.2f}%")
    
    # assert that at least one signal was generated by one of the signal funcs
    assert (signal_count > 0) or (enhanced_count > 0) or (breakout_count > 0)

def test_backtest_with_signals():
    """Test the backtesting with signal generation."""
    print("\nTesting backtest with signal generation...")
    
    # Create CSV file with synthetic data
    df = create_synthetic_data(bars=200, trend_up=True)
    
    with tempfile.NamedTemporaryFile(mode='w', suffix='.csv', delete=False) as f:
        # Ensure the index column is named 'ts' so load_csv recognizes it
        df.index.name = 'ts'
        df.reset_index().to_csv(f.name, index=False)
        csv_path = f.name
    
    # Import and run the backtest CLI helper from scripts/run_backtest.py
    import importlib.util
    import pytest
    base_dir = os.path.abspath(os.path.dirname(__file__))
    script_path = os.path.join(base_dir, 'scripts', 'run_backtest.py')
    if not os.path.exists(script_path):
        pytest.skip("scripts/run_backtest.py not present in this workspace")
    spec = importlib.util.spec_from_file_location('run_backtest', script_path)
    run_backtest_mod = importlib.util.module_from_spec(spec)
    assert spec is not None and spec.loader is not None
    spec.loader.exec_module(run_backtest_mod)  # type: ignore
    run_backtest = run_backtest_mod.run_backtest
    build_parser = run_backtest_mod.build_parser

    try:
        # Create arguments for CSV backtest with SMA cross strategy
        parser = build_parser()
        args = parser.parse_args([
            '--source', 'csv',
            '--path', csv_path,
            '--strategy', 'sma_cross',
            '--tp', '0.02',
            '--sl', '0.01',
            '--hold', '10'
        ])

        # Run backtest
        results = run_backtest(args)

        print(f"Backtest results:")
        print(f"  Total trades: {results.get('total_trades', 0)}")
        print(f"  Win rate: {results.get('win_rate_pct', 0):.2f}%")
        print(f"  PnL: {results.get('pnl', 0):.2f}")

        # assert that run_backtest completed and returned a dict-like result
        assert isinstance(results, dict)
        # support both legacy and current key names
        assert ('total_trades' in results) or ('trades' in results)
        assert ('pnl' in results) or ('final_balance' in results)
    finally:
        # Clean up temp file
        if os.path.exists(csv_path):
            os.unlink(csv_path)

def test_electron_file_paths():
    """Test that Electron app files exist and are properly structured."""
    print("\nTesting Electron app file structure...")
    
    electron_dir = os.path.join(repo_root, 'dashboard', 'electron-app')
    files_to_check = [
        'main.js',
        'package.json',
        'preload.js',
        'renderer/index.html'
    ]
    
    all_exist = True
    if not os.path.isdir(electron_dir):
        import pytest
        pytest.skip("Electron app directory not present; skipping electron file checks")
    for file in files_to_check:
        path = os.path.join(electron_dir, file)
        exists = os.path.exists(path)
        print(f"  {file}: {'✅' if exists else '❌'}")
        if not exists:
            all_exist = False
    
    if all_exist:
        print("  All Electron files present - 'Cannot GET /' issue likely resolved")
    assert all_exist

def main():
    """Run all tests."""
    print("="*60)
    print("TRADING BOT FUNCTIONALITY TEST")
    print("="*60)
    
    # This module is executed by pytest; keep main for direct runs but don't
    # use return values from tests. The individual test_* functions above
    # already include assertions and will be picked up by pytest.


if __name__ == '__main__':
    # run main for manual debugging (not used by pytest)
    try:
        main()
    except AssertionError as e:
        print('One or more checks failed:', e)
        sys.exit(1)
    sys.exit(0)