"""Core domain types shared by trading strategies.

This module defines the lightweight data structures that strategies use to
communicate with the rest of the trading system.  They intentionally avoid any
broker-specific concerns so they can be reused across backtesting, live
trading, and simulation environments.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Protocol


@dataclass(slots=True)
class Bar:
    """Market data bar for a single symbol."""

    ts: int
    """Unix timestamp for the bar close."""

    open: float
    """Opening price of the bar."""

    high: float
    """Highest traded price during the bar."""

    low: float
    """Lowest traded price during the bar."""

    close: float
    """Closing price of the bar."""

    volume: float
    """Traded volume during the bar."""


@dataclass(slots=True)
class OrderIntent:
    """Intent to place an order generated by a strategy."""

    idemp_key: str
    """Idempotency key used to deduplicate submissions."""

    symbol: str
    """Symbol the order targets."""

    side: str
    """``"buy"`` or ``"sell"``."""

    qty: float
    """Desired quantity in asset units."""

    type: str
    """``"market"`` or ``"limit"`` order type."""

    limit_price: Optional[float] = None
    """Limit price for limit orders; ignored for market orders."""

    meta: Dict[str, Any] = field(default_factory=dict)
    """Additional metadata useful for downstream processing."""


class Strategy(Protocol):
    """Interface that trading strategies must implement."""

    name: str
    symbols: List[str]

    def on_bar(self, bars: Dict[str, Bar]) -> List[OrderIntent]:
        """Handle a batch of new market data bars."""

    def on_fill(self, fill: Dict[str, Any]) -> None:
        """Handle order fill notifications."""

    def risk_state(self) -> Dict[str, Any]:
        """Return the current risk state snapshot."""


__all__ = ["Bar", "OrderIntent", "Strategy"]

